# Abstract

Education is considered a key tool for social mobility and equality of opportunities. However, despite the widespread value of education, disparities in educational outcomes persist over time. This paper is guided by the following research questions: To what extent are such educational disparities justified in society? Is the justification of educational inequality affected in periods of personal and social vulnerability, as in the COVID pandemic? And, what are the main factors driving this kind of justification? The Chilean case offers an interesting context for this study given its high economic inequality, deep neoliberal policies, and commodification of social services such as education. This economic and cultural environment has promoted meritocratic ideals, whereby individual talent and effort are considered key to get ahead in life, disregarding opportunities linked to social origin. The central argument of this article is that the justification of inequalities weakens during periods of vulnerability and crisis (such as the health and economic crisis resulting from the COVID-19 pandemic). Furthermore, we argue that such changes could be linked to a challenge of meritocratic ideals. For testing the research hypotheses we estimate a series of longitudinal multilevel models with data from a Chilean longitudinal panel survey (2016 – 2023, 6 waves, N = 2,927). Whereas we find support for the association between the perception of meritocracy and justification of inequality, the analyses that involved changes over time showed an increase in the justification of inequality in education. The discussion of these results delves into the social consequences of justifying inequality in a sensitive area as education, as well as the persistence of meritocratic ideals despite challenging events.\newline
  **Keywords**: meritocracy, social inequality, inequality justification, COVID-19

# Introduction

Despite the widespread recognition of education as a key factor for social mobility and equality of opportunities, disparities in this domain are far from being eliminated. As the last PISA report points out, “Socio-economically disadvantaged students are seven times more likely than advantaged students to score below Level 2 in mathematics on average across OECD countries” [@oecd_pisa_2023]. Furthermore, empirical evidence from social science research has revealed an exacerbation of educational inequalities across various domains, such as family socioeconomic status, gender, ethnicity, and migratory background, particularly after COVID-19 [@darmody_impacts_2021]. Nevertheless, and despite the consistent empirical evidence on educational inequalities and their consequences, research on distributive justice indicates remarkable individual differences in the justification of unequal access to education [@lee_fairness_2023]. In the present paper, we argue that the perception of meritocracy in society might play a role in the justification of economic inequalities in this particular domain. We examine this association in the context of COVID 19 in Chile, a period characterized by several challenges regarding the political and economic system that could have affected the way in which the role of individual performance and social outcomes are deemed.

The Chilean case is particularly relevant when it comes to the study of inequalities in education. The country is characterized by a high level of economic inequality associated with the privatization and commodification of several social policy domains, among them the educational system [@bellei_estudio_2013; @corvalan_mercado_2016]. The neoliberal reforms implemented during and since the military dictatorship (1973-1989) have deepened educational policies based on private subsidies, achievement incentives, selection, and segregation [@joiko_cuasimercado_2019]. Previous research in Chile has emphasized the concept of an "educational market" [@corvalan_mercado_2016], characterized by selection, competition, and the provision of goods and services associated with payment capacities. Many studies have addressed this problem from economic, political, and sociological perspectives, generating relevant evidence on their academic and social consequences [@ramos_educacion_2022]. Likewise, massive social mobilizations in the country (particularly in 2006, 2011, and 2018) have had educational inequalities as one of the main targets, putting pressure on governments towards a series of reforms that have advanced free higher education reforms and have diminished the role of private actors in the educational system [@donoso_when_2016; @reyes-housholder_chile_2019].

This research endeavors to dissect the nuanced alterations in the justifications for educational disparities within the Chilean framework. Central to our investigation is the premise that the rationale underpinning these inequalities experiences a significant recalibration during periods of vulnerability and crises, specifically under the unprecedented strains of the global health and economic cataclysm triggered by the COVID-19 pandemic [@hankivsky_introduction_2022;@breznau_welfare_2021]. A pertinent aspect of this discourse is articulated in the works of Mijs [-@mijs_stratified_2016;-@mijs_visualizing_2018], showing the interplay between meritocratic beliefs and the legitimization of disparities, as well as the potential erosion of meritocratic principles amidst crises. This line of research has highlighted how meritocratic beliefs are associated with justifying unequal access to resources and rewards in society, by legitimizing social hierarchies in which those who already have resources and advantages are more likely to succeed [@sandel_tyranny_2020;@mcnamee_meritocracy_2004;@hadjar_meritokratie_2008]. Within this framework, we point out that periods of vulnerability (such as the health and economic crisis resulting from the COVID-19 pandemic) could weaken the justification of social inequalities, a change that would be at least in part linked to a challenge of the meritocratic ideals.  
