# Inequality, beliefs and justification

The justification of economic inequalities is a controversial field of study. As equality is usually considered a synonym of justice in common sense, the idea that someone could be willing to justify inequalities seems (in principle) far from what is considerably reasonable. Nevertheless, and as pointed out by Barry, the whole normative discussion in social justice can be conceived as “the defensibility of unequal relations between people” [-@barry_theories_1989, p. 3], whereby empirical research has consistently shown strong variations between individuals and societies regarding inequality justification [@trump_income_2018;@kelley_legitimate_2021;@mijs_paradox_2021]. Both theoretical and empirical approaches have been able to establish a clear difference between inequality and justice, which opens the question of to what extent inequality can be tolerated or even justified.

The field of studies of subjective economic inequality has been extensively developed in the social sciences, particularly in the area of social justice research [@Resh2016]. From a sociological point of view, the works of @kluegelBeliefsStratification1981 can be considered pioneers in framing a research area comprising perceptions, beliefs, and justifications in topics such as inequality of opportunities, poverty, and distributive justice. Theoretically, the authors understand the concept of "beliefs" in a "broad sense to refer to the information (veridical or non-veridical) about a phenomenon that an individual uses as a basis both for inferring other information and for action." [@kluegelBeliefsStratification1981, p. 30]. However, the literature has strained the concept of "beliefs" by more specific distinctions around the individual and structural dimensions of economic inequality. In this regard, @wegenerIllusionDistributiveJustice1987 has suggested that perceptions of social status and reward hierarchy are relative to the observer's status in such hierarchies [@wegenerIllusionDistributiveJustice1987, p. 2]. This approach established that status positions influence how people perceive things _are_ and, in turn, these perceptions anchor how people evaluate this inequality as just or unjust [@jassoJusticeEarningsNew1978]. Additionally, @janmaatSubjectiveInequalityReview2013 has suggested more detailed conceptual distinctions about how people perceive economic inequality _is_, how they believe or prefer it _should be_, and the process of evaluating such differences as fair.

 Theoretically, @liebigSociologyJustice2016 establish three fundamental distinctions in justice attitudes in the field of sociological justice research. First, _order-related attitudes_ refer to individual motives that explain preferences for resource allocation based on the principles of equality, need, or entitlement. Second, _procedural justice attitudes_ account for the degree of acceptance of unfavorable outcomes under conditions in which the procedure under which those decisions were made is considered fair (e.g., opportunities). Finally, they can be _outcome-related attitudes_ which refer primarily to the economic resources that a person currently obtains and the set of collective commitments associated with possessing those resources (e.g., transfers or taxes). Within this framework, we conceptualize the justification of inequality in the first area of order-related attitudes, as it expresses preferences for resource allocation that can be associated with concepts that reflect different distributive principles [@kluegel_social_1995;@sonhing_merit_2011]

An important finding in the area of order-related attitudes is that beliefs about inequality are stratified by social status [@janmaatSubjectiveInequalityReview2013; @kluegelBeliefsInequalityAmericans1986]. The evidence suggests that advantaged positions in terms of socioeconomic status, such as income, education, or occupational prestige, are associated with preferences for less egalitarian class imageries [@Evans1992;@Evans2017] and greater justification of salary gaps [@hadler_why_2005;@kelley_legitimate_2021]. Nevertheless, and in contrast to this perspective, it has been argued that human beings are intrinsically motivated to justify the system they inhabit, even when the information available to them points in the opposite direction [@jost_psychology_2003;@vandertoorn_twenty_2014]. Individuals would be generally disposed to justify the economic status quo regardless of self- and group economic interest because their support partially depends on their beliefs in system-justifying ideologies [@trump_when_2020]. As a result, what has been suggested is that low-status might perceive the status quo as just as they are more strongly attached to dominant ideologies, while high-status individuals are more prone to justify the system to a greater extent because it favors their interests and dominant position [@jost_theory_2020]. 

Another factor that has been linked to inequality beliefs is the perception of economic inequality [@kelleyLegitimationInequalityOccupational1993; @osberg_fair_2006;@castillo_perception_2022]. Studies in this matter have argued that perceived economic inequality functions as an anchor for the justifications of inequality because if these inequalities are indeed seen as fair in their generative processes, then they will be considered as just [@wegenerIllusionDistributiveJustice1987; @Wegener1990]. Thus, both the role of social status and economic inequality perceptions have found support in correlational [@Castillo2012a_justice;@schroder_income_2017], as well as in experimental studies that have manipulated inequality perception [@iturra_percepcion_2023;@trump_income_2018]. In addition, normative or value-driven mechanisms can also explain to what extent people justify inequality. For instance, studies suggest that justice ideologies such as individualism or egalitarianism can mediate the influence of individual status on income inequality justification [@Castillo2011]. Likewise, system justification ideologies can strengthen the influence of socioeconomic status on economic inequality preferences [@garcia-sanchez_creencias_2022]. Altogether, these studies have shown that not only socio-structural factors influence what people believe regarding the distribution of economic resources, but their normative stances and perceptions can also determine preferences for economic inequality in diverse domains.

# The justification of educational inequality 

Studies addressing inequality justification have assessed the support for market ideologies, salary gaps, and distributive preferences. A strand of this research has focused on specific policy areas such as health, pensions, and education,  attending to the degree of justification of market-based access to social services. For instance, @lindhPublicOpinionMarkets2015 found that public support for the market distribution of social services is generally low in most countries, implying that most people believe it is unfair for market forces to determine access to basic social services. Similarly, @busemeyer_welfare_2020 shows that high-income citizens are less supportive of expanding public spending on universal benefit schemes. Instead, they tend to prefer a public basic insurance scheme, even if it provides relatively more benefits to low-income individuals.

The study of inequality justification in the sphere of education is a rather specific and unattended field. Most studies on educational inequality relate performance indicators (such as grades and standardized test results) to stratification-related variables, whereby few refer specifically to if and how individuals tolerate and even justify educational inequalities. This is probably because in principle it seems counter-intuitive to think that someone would be willing to justify differences in such a sensitive area. This paradox is phrased by @confortiLegitimationInequalityAmerican1992 as “while equality is embraced as a value, inequality is accepted as a reality” (p.230).

In the area of empirical studies, the operationalization of educational inequality justification in terms of questionnaire items is diverse, and there is not a single instrument or scale dedicated specifically to this concept. Rather, some attitudinal surveys usually include education-related items that are posteriorly used as dependent or independent variables. Some examples are the International Social Survey Programme (ISSP) (_Is it just or unjust – right or wrong – that people with higher incomes can buy better education for their children than people with lower incomes?_), and the European Social Survey (ESS) 2018 (_Compared to other people in [country], I have had a fair chance of achieving the level of education I was seeking_). Although both questions have been used to measure the justification of educational inequality, they refer to different aspects. The ESS can be classified as reflexive, as the respondent is involved as a referent for the question, whereas the ISSP question is non-reflexive. Furthermore, ISSP refers to educational access, while the ESS refers to educational outputs.

Studies have addressed the justification of educational inequality from different conceptual perspectives and methodological strategies. Some perspectives emphasize the justification of differences between specific groups, finding for instance that Americans are more concerned about—and more supportive of proposals to close—wealth-based achievement gaps than Black-White or Hispanic-White gaps [@valantPoliticsAchievementGaps2016]. Other studies focus on the association between status differences and inequality justification in education, based on the rational premise that those who are worst-off would tend to show lower levels of justification [@stoilovaFairnessEducationalOpportunities2023]. However, most of the research in this area goes beyond status differences, focusing on how subjective factors such as perceptions and beliefs are related to different levels of justification.

The perception of economic inequality is one of the factors associated with the justification of educational inequality. As pointed out by @janmaatSubjectiveInequalityReview2013, justifications are usually confused under the labels of “beliefs” and “attitudes,” and their distinction from perceptions is relevant as it helps state that justifying a certain level of inequality requires taking into account which level of (perceived) inequality is first and foremost being recognized [@sonhing_merit_2011;@castillo_multidimensional_2023]. For instance, a recent study by @dayPerceivedIdealInequality2023 on the perception and justification of inequality in university endowments in the U.S. points out that individuals tend to underestimate the magnitude of existing inequality while simultaneously desiring greater equality. Furthermore, through an experiment, they demonstrate that information about inequality in university endowments (i.e., manipulating inequality perception) increases the perception of injustice in education. Results of this study are in line with the consistent evidence on biases related to the underestimation of economic inequality [@castillo_perception_2022;@gimpelson_misperceiving_2018]

Besides focusing on the relationship between perception and justification of educational inequality, another group of studies has addressed how the justification of inequality is associated with the support of different distributive principles. In an experiment by @igliozziFairShareEffects2024, they establish how the support for different justice principles (equity, equality, and need) is related to support for redistributive policies in domains such as education. They find that a larger system justification  [@jost_psychology_2003] is related to higher support for the principles of equity and equality (over need) in distributing educational outcomes, where equity was measured in terms of access to education related to performance ('Students who place within the highest 50% of testing scores from the previous year can attend the magnet school'). In the same line, @leeFairnessPerceptionsEducational2023 show that performance assessments (in what they call “neoliberal orientations”) predicted people's fair perceptions of educational inequality.

_Justificacion, inequality and meritocracy in the educational domain_

The relationship between performance and outputs brings us to the concepts of merit and meritocracy, key in educational justice research. The concept of meritocracy, coined by the sociologist Michael Young in his satirical work "The Rise of the Meritocracy" [-@young_rise_1962], has a rich history and multifaceted meaning. Young's term was initially used to critique a hypothetical future society where social and economic positions were entirely determined by individuals' merits, talents, and efforts, ostensibly eliminating the influence of inherited privilege. However, over time, the term has evolved to describe a social system where advancement and success are perceived as directly linked to one's abilities and achievements, sidelining inequalities of opportunities [@bell_politics_2020]. This would contribute to the justification of inequality in the educational domain [@sandel_tyranny_2020], as individual ability is often inherited, and educational attainment is influenced by family background [@goldin_meritocracy_2000].

Empirical research examining the relationship between meritocratic perceptions and the justification of educational inequality provides valuable insights into the dynamics shaping individuals' attitudes and beliefs. Some studies have explored the extent to which people believe that educational systems are meritocratic and how these perceptions influence their acceptance or rejection of educational disparities, as well as status differences [@McCoy2007]. This belief is particularly influential in educational institutions, where it not only encourages academic success but also legitimizes social and income inequality [@batruch_belief_2023]. Most of the evidence so far suggests that those who believe in a direct link between effort, talent, and educational success are more inclined to rationalize existing disparities in educational outcomes. However, empirical findings also reveal nuances in this relationship. For instance, studies show that when individuals perceive structural barriers, such as economic disparities or discrimination, as hindering the meritocratic ideal, they may be less likely to justify educational inequalities [@dayPerceivedIdealInequality2023]. This suggests that while meritocratic beliefs play a significant role, individuals' awareness of broader societal issues can mediate their willingness to rationalize educational disparities.

_This study_

The present research uses longitudinal survey data from 2016 to 2022 to asses changes in inequality justification. As there are measures before and after the COVID pandemic, firstly we explore to what extent it is possible to identify variations in inequality justification in this time frame. Although we are aware that it is not possible to make a causal claim given that this period is characterized by many other circumstances besides COVID, we argue that the increase of risk perceptions in critical situations (such as the pandemic) impacts public concerns about equality and redistribution [@breznau_welfare_2021]. Although the pandemic might have triggered such concerns mostly regarding health, we believe that other policy areas, such as education, could have been impacted in this period. Consistently, our first hypothesis is: 

$H_1$: The justification of educational inequalities decreases after the pandemic

Our second argument is based on the evidence that relates rational interests with justifications and preferences [@sonhing_failure_2019], expecting that:

$H_2$: Those with lower status characteristics show lower justification of educational inequalities

Thirdly, we address inequality perception. As referred to above, the justification of inequality requires, first and foremost, that such inequality is recognized. As a larger inequality in this domain threatens a basic equality ideal, the corresponding hypothesis in this case is:

$H_3$: A larger inequality perception is negatively associated with the justification of educational inequalities.

Our fourth hypothesis refers to the central concept of meritocracy. As meritocracy justifies inequalities based on performance, we expect that:

$H_4$: Higher meritocratic perceptions are positively related to the justification of educational inequalities.

Finally, and in line with hypotheses 1 and 4, we explore interactions between meritocracy and inequality justification over time. As COVID-19 pandemic has affected the structural opportunities to attend schools, universities, or workplaces, the ideal of meritocracy might have been challenged. As a consequence, the justification of inequality could show a decrease over time:

$H_5$: The positive association between meritocracy and inequality justification mitigates along time
