# Discussion and conclusions

Our research sought to examine the relationship between the perception of meritocracy and the justification of inequality in education from a longitudinal perspective amid the health crisis generated by the COVID-19 pandemic. In general, our results showed mixed evidence about our hypotheses. Whereas we find support for the association between the perception of meritocracy and justification of inequality across time, the analyses that involved changes in justification of inequality are against our initial proposal. We argued that in times of crisis, greater exposure to risk due to the health context would result in a lower justification of inequality by citizens. In this regard, longitudinal models showed that the justification of inequality in education is far from being linear, and whereas a decreasing pattern was found between 2017 and 2019, there is a striking increase in the last measurement point (2022), after the peak of the COVID pandemic. As we mentioned at the beginning, given our data limitations it is not possible to attribute such changes only to the pandemic and the related economic and social crises. As in the Chilean case, the pandemic period occurred along with a constitutional process, disentangling different forces driving public opinion it becomes difficult and deserves further qualitative and quantitative studies. A closer look to the political environment during the last year in the country could give additional hints. Some recent studies have argued that the election of a far left-wing constitutional assembly during this period generated a backslash effect, mainly due to several scandals that led to the delegitimation of this assembly. This could have driven preferences in a conservative direction, which was reflected in the election of a right-wing second assembly after the failed first constitutional process [@palanza_chile_2023;@sazo_chile_2023].

Regarding the status position, our central hypothesis was that individuals in more advantaged situations and with greater resources would tend to defend their interests and justify greater education inequality ($H_2$). In this regard, our results show a positive and robust relationship between income and the justification of inequality, which would align with our original hypothesis based on the rational interests of the better-off that would lead to a larger inequality justification. Besides status, we also considered inequality perception, as the literature on attitudes toward inequality has argued that a greater justification of inequality is associated with its perceived magnitude ($H_3$). Consistent with this hypothesis, our results showed that, throughout the years, a larger perceived economic inequality motivates a lower justification of inequality in education.

The main focus of this study was on the relationship between meritocracy and justification of inequality, arguing that those who perceive that the society in which they live complies with meritocratic principles, would be more inclined to justify inequality in education ($H_4$). At first look, the results are consistent with the hypothesis; however, some nuances are worth attending concerning different aspects of meritocracy, namely effort and talent. Our results are favorable for the effort dimension but not confirmed for the talent dimension. In other words, the perception of meritocracy in terms of rewarded effort is more relevant in justifying access to education than the perception of talent. This could be explained as that talent could be more associated with luck in terms of random assignment, and in this terms would not be enough reason (as it is effort) to justify educational inequality.

Finally, as our first hypothesis supported, we expected that the relationship between meritocratic perceptions and justification would tend to diminish over time. However, longitudinal evidence shows that the perception of meritocracy linked to effort strengthens its relation with the justification of inequality in education, against the temporal change hypothesis ($H_5$). In other words, meritocracy seems to gain force concerning justifying inequality and not the other way around as we expected given the social context in the post-covid era. An alternative interpretation is that in times of high exposure to risk, people tend to stick more to narratives that provide greater security regardless of the rest of the society - such as individual effort -, which might also be accompanied by lower degrees of solidarity to safeguard the well-being of themselves and their surrounding close peers. Again, this certainly needs further studies that include additional specific conceptual and methodological approaches to this phenomenon.

Among the limitations of our study, we can mention at least three. First, we know that inequalities in education can manifest themselves in terms of outcomes as well as in areas such as access to social services in education as part of welfare policies. In this regard, the construct that we have captured with our indicator can be framed more in the latter, while the evaluation of justice involved in this process does not consider aspects such as equality of educational opportunities or observable outcomes such as the performance of individual or educational institutions. Second, as it has been established by recent research [@castillo_multidimensional_2023], the perception of meritocracy can be understood through individual attributions regarding effort and talent, but also as a function of structural aspects such as family of origin status or social capital. In this sense, the available measurements restricted us to the use of single indicators for effort and talent, and further research should consider improving the measurement quality in this regard. Finally, there are limitations involving the longitudinal dimension of the data used. Given constraints for data collection during the pandemic, the ELSOC study had to shorten the questionnaire in 2021 and unfortunately, the educational justice indicator was excluded from that survey. Consequently, the results of temporal change have to be considered carefully, and further data waves could give us more information on this matter.

The capabilities of the ELSOC longitudinal database are not limited to micro-level estimates. In this regard, thanks to the sampling strategy of the survey, it would be possible to make contextual estimates at the municipality level in future studies. For instance, statistical models could include contextual information from administrative data sources, allowing testing for hypotheses that include contextual socioeconomic inequality as well as its dynamics over time.  Furthermore, this dataset could be used for comparing inequality justification in policy areas besides education, such as health and pensions. Future studies may shed light on how meritocratic perceptions and beliefs affect differently such areas and their changes over time, which would give relevant hints from social sciences for the discussion about societal and cultural changes as well as their impacts on solidarity and social cohesion.

