---
title: Changes in the justification of educational inequalities. The role of perceptions of inequality and meritocracy during the COVID pandemic.
format:
  docx:
    number-sections: true
  html: 
    code-fold: true
    html-math-method: katex
    number-sections: true
  pdf:
    classoption: 10pt
    geometry: 
      - top=30mm
      - left=20mm
    template-partials: 
      - title.tex
    keep-tex: true
    number-sections: true
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
        \renewcommand\Affilfont{\small}
        \usepackage{mathptmx} % Times
editor: source
bibliography: "input/bib/merit-edjust.bib"
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
      - ref: 2
      - ref: 3
  - name: Julio Iturra
    orcid: 0000-0003-1993-3479
    email: julioiturrasanhueza@gmail.com 
    affiliations:
      - ref: 4
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 2
affiliations: 
  - id: 1
    name: Universidad de Chile
  - id: 2
    name: Centro de estudios del conflicto y cohesión social (COES)
  - id: 3
    name: Núcleo milenio de desigualdades y oportunidades digitales (NUDOS)
  - id: 4
    name: International Graduate School of Social Sciencies (BIGSSS), University of Bremen, Germany
citeproc: true
abstract: | 
  Education is considered a key tool for social mobility and equality of opportunities. However, despite the widespread value of education, disparities in educational outcomes persist over time. This paper is guided by the following research questions: To what extent are such educational disparities justified in society? Is the justification of educational inequality affected in periods of personal and social vulnerability, as in the COVID pandemic? And, what are the main factors driving this kind of justification? The Chilean case offers an interesting context for this study given its high economic inequality, deep neoliberal policies, and commodification of social services such as education. This economic and cultural environment has promoted meritocratic ideals, whereby individual talent and effort are considered key to get ahead in life, disregarding opportunities linked to social origin. The central argument of this article is that the justification of inequalities weakens during periods of vulnerability and crisis (such as the health and economic crisis resulting from the COVID-19 pandemic). Furthermore, we argue that such changes could be linked to a challenge of meritocratic ideals. For testing the research hypotheses we estimate a series of longitudinal multilevel models with data from a Chilean longitudinal panel survey (2016 – 2023, 6 waves, N = 2,927). Whereas we find support for the association between the perception of meritocracy and justification of inequality, the analyses that involved changes over time showed an increase in the justification of inequality in education. The discussion of these results delves into the social consequences of justifying inequality in a sensitive area as education, as well as the persistence of meritocratic ideals despite challenging events.\newline
  **Keywords**: meritocracy, social inequality, inequality justification, COVID-19
---

```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo=FALSE, warning = FALSE,message = FALSE, cache = TRUE,out.width = '85%',fig.pos= "H"
                       # , fig.align = 'center'
                       )
 # knitr::opts_knit$set(base.url = "../") #relative path for .html output file
 # knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
 options(scipen=999)
 options(kableExtra.auto_format = FALSE)
 rm(list=ls())
 options(knitr.kable.NA = '')
 options(knitr.graphics.error = FALSE)
 Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r}
# This document was last modified at {{< modified >}}
# 
# and it was last rendered at {{< now >}}

```


{{< include 01-introduction.qmd >}}

{{< include 02-antecedentes.qmd >}}

{{< include 03-methods.qmd >}}

{{< include 04-analisis.qmd >}}

{{< include 05-discussion.qmd >}}

# References

::: {#refs}
:::

{{< include 07-apendice.qmd >}}
