---
title: "Preparación de datos"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: hide
    number_sections: yes
editor_options:
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	results = "asis",
	message = FALSE,
	warning = FALSE, 
	fig.height = 18, 
	fig.width = 11, 
	cache = TRUE
)
options(scipen=9999) # desactivar notacion cientifica
remove(list = ls()) #limpieza del entorno de trabajo
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

# Descriptive analysis

## Univariate

```{r tab-desc, results="asis", warning=FALSE}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# Css
st_css()
st_options(lang = "en",
           footnote = NA,
           bootstrap.css = F,
           custom.css = here::here("input/css/dfsummary.css"),
           dfSummary.custom.1 = NA
           )  

# Df variables nivel 1
# df<- dfSummary(df_study1_long %>% select(in_simpat:edad),
#                plain.ascii = FALSE,
#                style = "grid",
#                tmp.img.dir = "/tmp",
#                graph.magnif = TRUE,
#                headings = F,  # encabezado
#                varnumbers = F, # num variable
#                labels.col = T, # etiquetas
#                na.col = F,    # missing
#                graph.col = T, # plot
#                valid.col = T, # n valido
#                col.widths = c(700,10,10,10,10)
#                )
# df$Variable <- NULL # delete variable column
# view(df,
#      file = here::here("output/tables/desc01.html")
#      ) # Ver tabla en un archivo HTML
# webshot::webshot(url =here::here("output/tables/desc01.html"),
#         file =here::here("output/tables/desc01.png")) # Remover archivo HTML
# # print(df, method = "render")

# Df variables nivel 1 __________________________________________________________
df_study1 <- df_study1_long_comunas %>% select(just_educ:merit_talent,
                                               ahead_family:sexo) 
lab_study1 <- sjlabelled::get_label(df_study1) 
df_study1 <- df_study1 %>% na.omit() %>% sjlabelled::set_label(lab_study1)

df<- dfSummary(x = df_study1,
               plain.ascii = FALSE,
               style = "grid",
               tmp.img.dir = "/tmp",
               graph.magnif = TRUE,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = T, # plot
               valid.col = T, # n valido
               col.widths = c(700,10,10,10,10,10)
               )
# df$Variable <- NULL # delete variable column
view(df,
     file = here::here("output/tables/desc02.html")
     ) # Ver tabla en un archivo HTML
webshot::webshot(url =here::here("output/tables/desc02.html"),
        file =here::here("output/tables/desc02.png")) # Remover archivo HTML
# print(df, method = "render")
```

## Correlation

```{r cor-plot, fig.dim=c(10,6)}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               sjPlot,
               sjmisc,
               summarytools,
               lavaan
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# Full sample_______________________________________________________________________
mat_full<- 
df_study1_long_comunas %>%
  # filter(ola==1) %>%
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_full <- as.matrix(mat_full$rho)
diag(cor_full) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_full) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_full) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_full,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Full sample")

# Wave 1_______________________________________________________________________
mat_1<- 
df_study1_long_comunas %>%
  filter(ola==1) %>%
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_1 <- as.matrix(mat_1$rho)
diag(cor_1) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_1) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_1) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_1,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 1")

# Wave 2_______________________________________________________________________
mat_2<-   
df_study1_long_comunas %>%
  filter(ola==2) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_2 <- as.matrix(mat_2$rho)
diag(cor_2) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_2) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_2) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_2,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 2")


# Wave 3_______________________________________________________________________
mat_3 <- 
df_study1_long_comunas %>%
  filter(ola==3) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor()  

cor_3 <- as.matrix(mat_3$rho)
diag(cor_3) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_3) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_3) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_3,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 3")

# Wave 4_______________________________________________________________________
mat_4 <- 
df_study1_long_comunas %>%
  filter(ola==4) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 


cor_4 <- as.matrix(mat_4$rho)
diag(cor_4) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_4) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_4) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_4,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 4")


# Wave 6_______________________________________________________________________
mat_6 <- 
df_study1_long_comunas %>%
  filter(ola==6) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_6 <- as.matrix(mat_6$rho)
diag(cor_6) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_6) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_6) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_6,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 6")
```

# Models

## A. Education distribution justice

```{r distribution-educ}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study1_long_comunas %>%
  select(idencuesta,ola,comuna,just_educ:merit_talent, ahead_family:sexo, ginilag22_17, gini_ypch_2022) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
# Hipotesis
h1 <- "ola"
h2 <- "ola+merit_effort+merit_talent"
h3 <- "ola+merit_effort+merit_talent+ahead_family+ahead_educ+ahead_ambition+ahead_hardwork"
h4 <- "ola+merit_effort+merit_talent+ahead_family+ahead_educ+ahead_ambition+ahead_hardwork+ginilag22_17+gini_ypch_2022"
h5 <- "ola+merit_effort+merit_talent+ahead_family+ahead_educ+ahead_ambition+ahead_hardwork+ginilag22_17+gini_ypch_2022+educ+quintil1+ess+pos_id+edad+sexo"

# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1)
educ1 <- lmer(formula(paste0("just_educ~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ2 <- lmer(formula(paste0("just_educ~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ3 <- lmer(formula(paste0("just_educ~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ4 <- lmer(formula(paste0("just_educ~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ5 <- lmer(formula(paste0("just_educ~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study1)

#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(educ.null, educ1, educ2, educ3, educ4, educ5),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
                custom.coef.names = c("Intercepto",
                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
                                      "ola 2018",
                                      "ola 2019",
                                      "ola 2022",
                                      "Merito: esfuerzo",
                                      "Merito: Inteligencia",
                                      "Goahead: Familia",
                                      "Goahead: educacion",
                                      "Goahead: ambicion",
                                      "Goahead: trabajo duro",
                                      "Cambio gini 2022-2017",
                                      "Gini comunal 2022",
                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
                                      "Ed. técnica",
                                      "Ed. universitaria",
                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
                                      "Quintil 3",
                                      "Quintil 4",
                                      "Quintil 5",
                                      "Quintil NA",
                                      "Estatus social subjetivo",
                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
                                      "Pos. política: Derecha",
                                      "Pos. política: No se identifica",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Mujer <br> <i>(Ref. Hombre)</i>"
                              )
          #omit.coef = omit
          )
```

## B. Pension distribution justice

```{r distribution-pension}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study1_long_comunas %>%
  select(idencuesta,ola,comuna,just_pension:merit_talent, ahead_family:sexo, ginilag22_17,gini_ypch_2022) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )

# B. Pension distributive justice
pension.null <- lmer(formula(paste0("just_pension~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1)
pension1 <- lmer(formula(paste0("just_pension~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
pension2 <- lmer(formula(paste0("just_pension~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
pension3 <- lmer(formula(paste0("just_pension~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
pension4 <- lmer(formula(paste0("just_pension~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
pension5 <- lmer(formula(paste0("just_pension~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study1)

#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(pension.null, pension1, pension2, pension3, pension4, pension5),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
                custom.coef.names = c("Intercepto",
                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
                                      "ola 2018",
                                      "ola 2019",
                                      "ola 2022",
                                      "Merito: esfuerzo",
                                      "Merito: Inteligencia",
                                      "Goahead: Familia",
                                      "Goahead: educacion",
                                      "Goahead: ambicion",
                                      "Goahead: trabajo duro",
                                      "Cambio gini 2022-2017",
                                      "Gini comunal 2022",
                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
                                      "Ed. técnica",
                                      "Ed. universitaria",
                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
                                      "Quintil 3",
                                      "Quintil 4",
                                      "Quintil 5",
                                      "Quintil NA",
                                      "Estatus social subjetivo",
                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
                                      "Pos. política: Derecha",
                                      "Pos. política: No se identifica",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Mujer <br> <i>(Ref. Hombre)</i>"
                              )
          #omit.coef = omit
          )
```

## C. Health distribution justice

```{r distribution-health}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study1_long_comunas %>%
  select(idencuesta,ola,comuna,just_salud:merit_talent, ahead_family:sexo, ginilag22_17,gini_ypch_2022) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )

# C. Health distributive justice
salud.null <- lmer(formula(paste0("just_salud~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1)
salud1 <- lmer(formula(paste0("just_salud~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
salud2 <- lmer(formula(paste0("just_salud~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
salud3 <- lmer(formula(paste0("just_salud~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
salud4 <- lmer(formula(paste0("just_salud~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
salud5 <- lmer(formula(paste0("just_salud~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study1)

#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(salud.null, salud1, salud2, salud3, salud4, salud5),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
                custom.coef.names = c("Intercepto",
                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
                                      "ola 2018",
                                      "ola 2019",
                                      "ola 2022",
                                      "Merito: esfuerzo",
                                      "Merito: Inteligencia",
                                      "Goahead: Familia",
                                      "Goahead: educacion",
                                      "Goahead: ambicion",
                                      "Goahead: trabajo duro",
                                      "Cambio gini 2022-2017",
                                      "Gini comunal 2022",
                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
                                      "Ed. técnica",
                                      "Ed. universitaria",
                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
                                      "Quintil 3",
                                      "Quintil 4",
                                      "Quintil 5",
                                      "Quintil NA",
                                      "Estatus social subjetivo",
                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
                                      "Pos. política: Derecha",
                                      "Pos. política: No se identifica",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Mujer <br> <i>(Ref. Hombre)</i>"
                              )
          #omit.coef = omit
          )
```

## D. Income differences are too large

```{r inequality}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study2_long_comunas.RData"))

# generate analytical sample
df_study2 <- 
  df_study2_long_comunas %>%
  select(idencuesta,ola,comuna,des_perc:merit_talent, ahead_family:sexo, ginilag22_17,gini_ypch_2022) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )

# C. Health distributive justice
des.null <- lmer(formula(paste0("des_perc~","1 + (1|idencuesta)+(1|comuna)")),data = df_study2)
des1 <- lmer(formula(paste0("des_perc~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study2)
des2 <- lmer(formula(paste0("des_perc~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study2)
des3 <- lmer(formula(paste0("des_perc~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study2)
des4 <- lmer(formula(paste0("des_perc~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study2)
des5 <- lmer(formula(paste0("des_perc~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study2)

#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(des.null, des1, des2, des3, des4, des5),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
                custom.coef.names = c("Intercepto",
                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
                                      "ola 2018",
                                      "ola 2019",
                                      "Ola 2021",
                                      "ola 2022",
                                      "Merito: esfuerzo",
                                      "Merito: Inteligencia",
                                      "Goahead: Familia",
                                      "Goahead: educacion",
                                      "Goahead: ambicion",
                                      "Goahead: trabajo duro",
                                      "Cambio gini 2022-2017",
                                      "Gini comunal 2022",
                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
                                      "Ed. técnica",
                                      "Ed. universitaria",
                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
                                      "Quintil 3",
                                      "Quintil 4",
                                      "Quintil 5",
                                      "Quintil NA",
                                      "Estatus social subjetivo",
                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
                                      "Pos. política: Derecha",
                                      "Pos. política: No se identifica",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Mujer <br> <i>(Ref. Hombre)</i>"
                              )
          #omit.coef = omit
          )
```

