---
title: "Analysis"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: hide
    number_sections: yes
editor_options:
  chunk_output_type: console
---
# Setup

```{r setup}
knitr::opts_chunk$set(
	echo = FALSE,
	results = "asis",
	message = FALSE,
	warning = FALSE, 
	fig.height = 18, 
	fig.width = 11, 
	cache = TRUE
)
options(scipen=9999) # desactivar notacion cientifica
remove(list = ls()) #limpieza del entorno de trabajo
```

```{css, echo=FALSE}
# /* expandir el espacio del documento*/
body .main-container {
      max-width: 1600px !important;
      width: 1600px !important;
    }
#/* expandir width de la TOC*/
div.tocify {
    width: 22% !important;
    max-width: 331px !important;
    max-height: 102% !important;
}
```

# Descriptive analysis

## Univariate

```{r tab-desc, results="asis", warning=FALSE}
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               ggplot2,
               sjPlot,
               tidyverse,
               ggalluvial,
               survey,
               shadowtext
               )
load(file = here::here("input/data-proc/df_study_t6_ind_comunas.RData"))

# Css
st_css()
st_options(lang = "en",
           footnote = NA,
           bootstrap.css = F,
           custom.css = here::here("input/css/dfsummary.css"),
           dfSummary.custom.1 = NA
           )  

# Df variables nivel 1
# df<- dfSummary(df_study1_long %>% select(in_simpat:edad),
#                plain.ascii = FALSE,
#                style = "grid",
#                tmp.img.dir = "/tmp",
#                graph.magnif = TRUE,
#                headings = F,  # encabezado
#                varnumbers = F, # num variable
#                labels.col = T, # etiquetas
#                na.col = F,    # missing
#                graph.col = T, # plot
#                valid.col = T, # n valido
#                col.widths = c(700,10,10,10,10)
#                )
# df$Variable <- NULL # delete variable column
# view(df,
#      file = here::here("output/tables/desc01.html")
#      ) # Ver tabla en un archivo HTML
# webshot::webshot(url =here::here("output/tables/desc01.html"),
#         file =here::here("output/tables/desc01.png")) # Remover archivo HTML
# # print(df, method = "render")

# Df variables nivel 1 _________________________________________________________
df_study1 <- df_study_long_t6_comunas %>% dplyr::select(ola,
                                               just_educ, merit_effort, merit_talent,
                                               ahead_family:educ, quintil1:sexo)

df_study1$ola <- factor(df_study1$ola,
         labels = c("2016","2017","2018","2019", "2022"))
df_study1$ola <- 
sjlabelled::set_label(x = df_study1$ola,
                      label = "Wave")

df_study1$sexo <- factor(df_study1$sexo,
         labels = c("Male", "Female"))
df_study1$sexo <- 
sjlabelled::set_label(x = df_study1$sexo,
                      label = "Gender")

for (i in c("just_educ",
            "merit_effort","merit_talent")) {
  df_study1[[i]] <- factor(df_study1[[i]],
                            levels = 1:5,
                            labels = c("Strongly disagree","Disagree",
                                       "Neither disagree nor agree",
                                       "Agree", "Strongly agree"))
}

for (i in c("ahead_family","ahead_educ",
            "ahead_ambition", "ahead_hardwork")) {
  df_study1[[i]] <- factor(df_study1[[i]],
                            levels = 1:5,
                           labels = c("Not at all important",
                                  "A little important",
                                  "Somewhat important",
                                  "Pretty important",
                                  "Very important"))
}

df_study1$just_educ <- 
sjlabelled::set_label(x = df_study1$just_educ, 
                      label = "Education distributive justice")

#
df_study1$merit_effort <- 
sjlabelled::set_label(x = df_study1$merit_effort, 
                      label = "People are rewarded for their efforts")

#
df_study1$merit_talent <- 
sjlabelled::set_label(x = df_study1$merit_talent, 
                      label = "People are rewarded for their intelligence")

#
df_study1$ahead_family <- 
sjlabelled::set_label(x = df_study1$ahead_family, 
                      label = "Coming from a wealthy family") 

#
df_study1$ahead_educ <- 
sjlabelled::set_label(x = df_study1$ahead_educ, 
                      label = "Having a good level of education") 

#
df_study1$ahead_ambition <- 
sjlabelled::set_label(x = df_study1$ahead_ambition, 
                      label = "Having ambition") 

#
df_study1$ahead_hardwork <- 
sjlabelled::set_label(x = df_study1$ahead_hardwork, 
                      label = "Hard work")

lab_study1 <- sjlabelled::get_label(df_study1) 
df_study1 <- df_study1 %>% na.omit() %>% sjlabelled::set_label(lab_study1)

df<- dfSummary(x = dplyr::select(df_study1, ola, just_educ, merit_effort, merit_talent, ahead_hardwork, ahead_educ, ahead_ambition, ahead_family, educ, quintil1, ess, pos_id, edad, sexo),
               plain.ascii = FALSE,
               style = "grid",
               tmp.img.dir = "/tmp",
               graph.magnif = TRUE,
               headings = F,  # encabezado
               varnumbers = F, # num variable
               labels.col = T, # etiquetas
               na.col = F,    # missing
               graph.col = T, # plot
               valid.col = F, # n valido
               col.widths = c(700,10,10,10)
               )
df$Variable <- NULL # delete variable column
summarytools::view(df,
     file = here::here("output/tables/desc02.html")
     ) # Ver tabla en un archivo HTML
webshot::webshot(url =here::here("output/tables/desc02.html"),
        file =here::here("output/tables/desc02.png")) # Remover archivo HTML
# print(df, method = "render")
```

```{r}
df_study1 <- df_study_long_t6_comunas %>% dplyr::select(idencuesta, ola, ponderador_long_total, segmento, estrato,
                                               just_educ, merit_effort, merit_talent,
                                               ahead_family:educ, quintil1:sexo)
df_study1 <- df_study1[complete.cases(df_study1$segmento), ]

df_study1$just_educ <- factor(df_study1$just_educ,
         labels = c("Strongly disagree", "Disagree", "Neither agree
nor disagree", "Agree", "Strongly agree"))

elsoc_diseno <- svydesign(ids = ~segmento, #muestreo por conglomerado a nivel de manzanas (segmento)
                          strata = ~estrato, #muestreo estratificado a nivel ciudad (estato)
                          weights = ~ponderador_long_total, #ponderador longitudinal
                          nest = TRUE,
                          data = df_study1)


#Paso 1
datos.justeduc <- data.frame((svytable(~just_educ + ola + idencuesta, elsoc_diseno, round = F))) %>% dplyr::filter(Freq>0)  %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit()

#Paso 2
etiquetas.justeduc <- data.frame((svytable(~just_educ + ola, elsoc_diseno, round = F))) %>% group_by(ola) %>% mutate(porcentaje=Freq/sum(Freq)) %>% na.omit() %>% 
  mutate(idencuesta = 1)
```

```{r alluvial}
alluvial_justeduc <- ggplot(datos.justeduc, aes(x = ola, fill = just_educ, stratum = just_educ,
                             alluvium = idencuesta, y = porcentaje))+
    ggalluvial::geom_flow(alpha = .66) + 
    ggalluvial::geom_stratum(linetype = 0) +
    scale_y_continuous(labels = scales::percent) + 
    ylab(label = NULL) +
    xlab(label = NULL) + 
    theme(legend.position = 'top',
          legend.title = element_blank(),
          plot.caption = element_text(hjust = 0)) +
    scale_fill_viridis_d(begin = 0, end = .95, direction = -1, option = 'viridis') +
    geom_shadowtext(data = etiquetas.justeduc, 
              aes(label = ifelse(porcentaje > 0.03 , scales::percent(porcentaje, accuracy = .1),"")),
              position = position_stack(vjust = .5),
              show.legend = FALSE,
              size = 4,
              color = rep('white'),
              bg.colour='grey30')+
  scale_x_discrete(labels = c(2016, 2017, 2018, 2019, 2022))

alluvial_justeduc

ggsave(alluvial_justeduc, file="output/graphs/alluvial_dep.png", height = 7, width = 8)
```



```{r bivariate-plots}
merit_plot <- df_study1 %>% 
  select(ahead_family, ahead_ambition, ahead_educ, ahead_hardwork, merit_talent, merit_effort) %>% 
  sjPlot::plot_stackfrq(weight.by = df_study1$ponderador_long_total,
                        expand.grid =TRUE,
                      geom.colors = 'Spectral',
                      show.total = FALSE, 
                      vjust=rep(c("bottom", "top", "bottom", "top", "bottom"),6),
                      legend.labels = c("Strongly disagree", "Disagree", "Neither agree
nor disagree", "Agree", "Strongly agree"),
                      axis.labels = c("Ahead family", "Ahead ambition", "Ahead education", "Ahead hardwork", "Merit talent", "Merit effort")
                      ) +
  theme_light() +
  theme(legend.position="bottom", text = element_text(size = 14))
merit_plot

ggsave(merit_plot, file="output/graphs/merit_plot.png", height = 7, width = 8)
```

```{r}
colors<- c("#f1eef6ff","#bdc9e1ff","#b3b3b3ff","#74a9cfff","#0570b0ff")
range <- c(.9, .8) 

p_effort<-
  dplyr::select(df_study1,
                merit_effort) %>%
  sjPlot::plot_likert(geom.colors = "PuBu",
                      geom.size = 0.8,
                      catcount = 5,
                      grid.range  =  range,
                      show.prc.sign = T,
                      reverse.colors = T,
                      reverse.scale = T,
                      show.n = FALSE,
                      intercept.line.color = "white")  +
  ggplot2::theme(legend.position = "bottom",
    text = ggplot2::element_text(size = 16))+
  ggplot2::scale_fill_manual(
    values = colors,
    breaks = c(1,2,3,4,5),
  ) +
  theme(legend.position = "none")

p_talent<-
  dplyr::select(df_study1,
                merit_talent) %>%
  sjPlot::plot_likert(geom.colors = "PuBu",
                      geom.size = 0.8,
                      catcount = 5,
                      grid.range  =  range,
                      show.prc.sign = T,
                      reverse.colors = F,
                      reverse.scale = T,
                      show.n = FALSE, 
                      intercept.line.color = "white")  +
  ggplot2::theme(legend.position = "bottom",
    text = ggplot2::element_text(size = 16))+
  ggplot2::scale_fill_manual(
    values = colors,
    breaks = c(1,2,3,4,5), 
    labels = c(
      "Strongly disagree",
      "Disagree",
      "Neither disagree nor agree",
      "Agree",
      "Strongly agree"
    )
  )
  

p_hardwork<-
  dplyr::select(df_study1,
                ahead_hardwork) %>%
  sjPlot::plot_likert(geom.colors = "PuBu",
                      geom.size = 0.8,
                      catcount = 5,
                      grid.range  =  range,
                      show.prc.sign = T,
                      reverse.colors = F,
                      reverse.scale = T,
                      show.n = FALSE,
                      intercept.line.color = "white")  +
  ggplot2::theme(legend.position = "bottom",
    text = ggplot2::element_text(size = 16))+
  ggplot2::scale_fill_manual(
    values = colors,
    breaks = c(1,2,3,4,5),
  ) +
  theme(legend.position = "none")  
  
p_educ<-
  dplyr::select(df_study1,
                ahead_educ) %>%
  sjPlot::plot_likert(geom.colors = "PuBu",
                      geom.size = 0.8,
                      catcount = 5,
                      grid.range  =  range,
                      show.prc.sign = T,
                      reverse.colors = F,
                      reverse.scale = T,
                      show.n = FALSE,
                      intercept.line.color = "white")  +
  ggplot2::theme(legend.position = "bottom",
    text = ggplot2::element_text(size = 16))+
  ggplot2::scale_fill_manual(
    values = colors,
    breaks = c(1,2,3,4,5),
  ) +
  theme(legend.position = "none")
  
p_ambition<-
  dplyr::select(df_study1,
                ahead_ambition) %>%
  sjPlot::plot_likert(geom.colors = "PuBu",
                      geom.size = 0.8,
                      catcount = 5,
                      grid.range  =  range,
                      show.prc.sign = T,
                      reverse.colors = F,
                      reverse.scale = T,
                      show.n = FALSE,
                      intercept.line.color = "white")  +
  ggplot2::theme(legend.position = "bottom",
    text = ggplot2::element_text(size = 16))+
  ggplot2::scale_fill_manual(
    values = colors,
    breaks = c(1,2,3,4,5),
  ) +
  theme(legend.position = "none")

p_family<-
  dplyr::select(df_study1,
                ahead_family) %>%
  sjPlot::plot_likert(geom.colors = "PuBu",
                      geom.size = 0.8,
                      catcount = 5,
                      grid.range  =  range,
                      show.prc.sign = T,
                      reverse.colors = F,
                      reverse.scale = T,
                      show.n = FALSE, 
                      intercept.line.color = "white")  +
  ggplot2::theme(legend.position = "bottom",
    text = ggplot2::element_text(size = 16))+
  ggplot2::scale_fill_manual(
    values = colors,
    breaks = c(1,2,3,4,5),   
    labels = c(
      "Not at all important",
      "A little important",
      "Somewhat 
important",
      "Pretty important",
      "Very important"
    )
  )
```
##### Create plot
```{r}
pacman::p_load(cowplot)
t <- 0.1
s <- 0.45
m <- 0.4
xs <- 0.25

caption <- 
  stringr::str_wrap(
    paste0("Note: Own elaboration based on ELSOC Survey ",
           "(n=",dim(na.omit(df_study1))[1],"). "),
    width = 100)

title <- cowplot::ggdraw() + 
  cowplot::draw_label(
    "Frequencies for meritocracy",
    fontface = 'bold',
    size = 15,
    x = 0,
    hjust = 0
  ) 

likert1<-   
  cowplot::add_sub(
    cowplot::plot_grid(
                       p_effort,
                       p_talent,
                       p_hardwork,
                       p_educ,
                       p_ambition,
                       p_family,
                       align = "hv",
                       axis = "a",
                       nrow = 7, #6 plots
                       ncol = 1, #1 column   
                       rel_heights = c(
                                       s,s,s,s,
                                       s,
                                       s) #fig size within plot
    ),
    label = "", # Caption: source and sample size
    size = 11,  # Caption font size
    hjust = 0# Caption align 
  ) %>% 
  cowplot::ggdraw()
jpeg(here::here("output/graphs/figure1.jpg"),
    # units = "cm",
    # res = 100,
    width = 800,
    height = 800)
likert1
dev.off()
```


justification education vs year


```{r}
just_educ_year = df_study1 %>%
  group_by(ola) %>%
  summarise(education = mean(just_educ, na.rm = T))

categorias_x <- c(2016, 2017, 2018, 2019, 2022)

educ_year_plot <- just_educ_year_survey %>% ggplot(aes(ola, education)) +
  theme_bw(base_size = 14) +
  geom_point(size = 4)+
  ylab("Justification of inequality") +
  xlab("Wave") +
  scale_x_discrete(labels = categorias_x) +
  ylim(1,3)
educ_year_plot

ggsave(educ_year_plot, file="output/graphs/educ_year_plot.png", width = 7, height = 7)
```

Bivariate descriptive by year

probar ponderadores longitudinales

```{r}
educ_effort_year = elsoc_diseno %>% filter(!is.na(merit_effort)) %>% 
  group_by(ola, merit_effort) %>%
  summarise(education = survey_mean(just_educ, vartype = "ci", na.rm = T)) %>% 
  ungroup()

educ_talent_year = elsoc_diseno %>% filter(!is.na(merit_talent)) %>% 
  group_by(ola, merit_talent) %>%
  summarise(education = survey_mean(just_educ, vartype = "ci", na.rm = T)) %>% 
  ungroup()

categorias_x <- c("Strongly disagree", "Disagree", "Neither agree 
nor disagree", "Agree", "Strongly agree")
categorias_f <- c(2016, 2017, 2018, 2019, 2022)

effort_educ_year_plot <- educ_effort_year %>% 
  ggplot(aes(factor(merit_effort), education, color = factor(ola), shape = factor(ola))) +
  theme_bw(base_size = 14) +
  geom_point(size = 4)+ 
  ylab("Justification of inequality") +
  xlab("Merit: effort") +
  ylim(1, 3) +
  scale_x_discrete(labels = categorias_x) +
  scale_color_discrete(labels = categorias_f, name="Wave") +
  scale_shape_discrete(labels = categorias_f, name="Wave")

effort_educ_year_plot

talent_educ_year_plot <- educ_talent_year %>% 
  ggplot(aes(factor(merit_talent), education, color = factor(ola), shape = factor(ola))) +
  theme_bw(base_size = 14) +
  geom_point(size = 4) +
  ylab("Justification of inequality") +
  xlab("Merit: talent") +
  ylim(1, 3) +
  scale_x_discrete(labels = categorias_x) +
  scale_color_discrete(labels = categorias_f, name="Wave") +
  scale_shape_discrete(labels = categorias_f, name="Wave")


talent_educ_year_plot

ggsave(effort_educ_year_plot, file="output/graphs/effort_educ_year.png", height = 7, width = 7)
ggsave(talent_educ_year_plot, file="output/graphs/talent_educ_year.png", height = 7, width = 7)


educ_effort_year <- educ_effort_year %>% pivot_longer("merit_effort", 
                              names_to="merit", 
                              values_to="value")

educ_talent_year <- educ_talent_year %>% pivot_longer("merit_talent", 
                              names_to="merit", 
                              values_to="value")

educ_merit_year <- rbind(educ_effort_year, educ_talent_year)

custom_labeller <- as_labeller(function(variable, value) {
  return(categorias_f[value])
})
categorias_z <- c("Effort", "Talent")
merit_educ_year <- educ_merit_year %>% 
  ggplot(aes(factor(value), education)) +
  theme_bw(base_size = 14) +
  geom_point(aes(color=merit, shape=merit), size=3) +
  ylab("Justification of inequality") +
  xlab("Merit") +
  ylim(1, 3) +
  facet_wrap(~factor(ola), scales = "free", labeller = custom_labeller) +
  scale_color_discrete(labels = categorias_z, name="Merit") +
  scale_shape_discrete(labels = categorias_z, name="Merit")
merit_educ_year

ggsave(merit_educ_year, file="output/graphs/merit_educ_year.png", height = 7, width = 7)
```


## Correlation

```{r cor-plot, fig.dim=c(10,6)}
rm(list=ls())
if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               sjPlot,
               sjmisc,
               summarytools,
               lavaan
               )
load(file = here::here("input/data-proc/df_study_t6_ind_comunas.RData"))

# Full sample_______________________________________________________________________
mat_full<- 
df_study_long_t6_comunas %>%
  # filter(ola==1) %>%
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_full <- as.matrix(mat_full$rho)
diag(cor_full) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_full) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_full) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
png("output/graphs/corr.png",width=600,height=300, pointsize = 10)
corrplot::corrplot(cor_full,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-")
dev.off()

ggsave(cor, file="output/graphs/cor.png")
# Wave 1_______________________________________________________________________
mat_1<- 
df_study1_long_comunas %>%
  filter(ola==1) %>%
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_1 <- as.matrix(mat_1$rho)
diag(cor_1) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_1) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_1) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_1,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 1")

# Wave 2_______________________________________________________________________
mat_2<-   
df_study1_long_comunas %>%
  filter(ola==2) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_2 <- as.matrix(mat_2$rho)
diag(cor_2) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_2) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_2) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_2,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 2")


# Wave 3_______________________________________________________________________
mat_3 <- 
df_study1_long_comunas %>%
  filter(ola==3) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor()  

cor_3 <- as.matrix(mat_3$rho)
diag(cor_3) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_3) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_3) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_3,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 3")

# Wave 4_______________________________________________________________________
mat_4 <- 
df_study1_long_comunas %>%
  filter(ola==4) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 


cor_4 <- as.matrix(mat_4$rho)
diag(cor_4) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_4) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_4) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_4,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 4")


# Wave 6_______________________________________________________________________
mat_6 <- 
df_study1_long_comunas %>%
  filter(ola==6) %>% 
  select(just_educ, # distributive justice
         merit_effort, merit_talent, # meritocracy
         ahead_family, ahead_ambition, ahead_educ, ahead_hardwork # go ahead
         ) %>% 
  psych::mixedCor() 

cor_6 <- as.matrix(mat_6$rho)
diag(cor_6) = NA #set diagonal values to NA
# Set Row names of the matrix
rownames(cor_6) <- c("A. Education distributive justice",
                     "B. People are rewarded for their efforts",
                     "C. People are rewarded for their intelligence",
                     "D. Go ahead: wealthy family",
                     "E. Go ahead: Having ambition",
                     "F. Go ahead: Good level of education",
                     "G. Go ahead: Hard work")
#set Column names of the matrix
colnames(cor_6) <-c("(A)", "(B)","(C)","(D)","(E)","(F)","(G)")
#Plot the matrix using corrplot
corrplot::corrplot(cor_6,
  method = "color",
  addCoef.col = "#000390",
  type = "upper",
  tl.col = "black",
  col=colorRampPalette(c("white","#0068DC"))(12),
  bg = "white",
  na.label = "-",
  title = "\n Wave 6")
```

# Models

## A. Education distribution justice

```{r distribution-educ}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study_t6_ind_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study_long_t6_comunas %>%
  select(idencuesta,ola,comuna, ponderador_long_total, just_educ, merit_effort, merit_talent, ahead_family:educ, quintil1:sexo, ginilag22_17, gini_ypch_2022, gini_ypch, prop_univ, gini_gc, prop_pagado,pagadolag22_16, total_mat_pagado, var_simce_comuna, prom_simce_comuna, univlag22_17) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
# Hipotesis
h1 <- "ola"
h2 <- "ola+merit_effort+merit_talent"
h3 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo"
h4 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17"
h5 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_univ"
h6 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+univlag22_17"
h7 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_univ+univlag22_17"
h8 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prom_simce_comuna"
h9 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+var_simce_comuna"
h10 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prom_simce_comuna+var_simce_comuna"
h11 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_pagado"
h12 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+pagadolag22_16"
h13 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_pagado+pagadolag22_16"

h13.1 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_pagado+pagadolag22_16+prom_simce_comuna+var_simce_comuna+prop_univ+univlag22_17+gini_ypch+ginilag22_17"



# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ1 <- lmer(formula(paste0("just_educ~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ2 <- lmer(formula(paste0("just_educ~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ3 <- lmer(formula(paste0("just_educ~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ4 <- lmer(formula(paste0("just_educ~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ5 <- lmer(formula(paste0("just_educ~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ6 <- lmer(formula(paste0("just_educ~",h6,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ7 <- lmer(formula(paste0("just_educ~",h7,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ8 <- lmer(formula(paste0("just_educ~",h8,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ9 <- lmer(formula(paste0("just_educ~",h9,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ10 <- lmer(formula(paste0("just_educ~",h10,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ11 <- lmer(formula(paste0("just_educ~",h11,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ12 <- lmer(formula(paste0("just_educ~",h12,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ13 <- lmer(formula(paste0("just_educ~",h13,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ13.1 <- lmer(formula(paste0("just_educ~",h13.1,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)



#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::knitreg(list(educ1, educ2, educ3, educ4, educ5, educ6, educ7,educ8,educ9,educ10,educ11,educ12,educ13,educ13.1),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
#                custom.coef.names = c("Intercepto",
#                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
#                                      "ola 2018",
#                                      "ola 2019",
##                                      "ola 2022",
#                                      "Merito: esfuerzo",
#                                      "Merito: Inteligencia",
##                                      "Goahead: Familia",
#                                      "Goahead: educacion",
#                                      "Goahead: ambicion",
#                                      "Goahead: trabajo duro",
#                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
#                                      "Ed. técnica",
#                                      "Ed. universitaria",
#                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
#                                      "Quintil 3",
#                                      "Quintil 4",
#                                      "Quintil 5",
#                                      "Quintil NA",
#                                      "Estatus social subjetivo",
#                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
#                                      "Pos. política: Derecha",
#                                      "Pos. política: No se identifica",
#                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
#                                      "Edad 50-64",
#                                      "Edad 65 o más",
#                                      "Mujer <br> <i>(Ref. Hombre)</i>",
#                                      "Gini comunal",
#                                      "Cambio gini 2022-2017",
#                                      "Proporción educ universitaria",
#                                      "Proporción matrícula privada",
#                                      "Total matrícula privada",
#                                      "Varianza Simce comuna",
#                                      "Promedio Simce comuna"
                                    
                              )
          #omit.coef = omit

```

## A2. Education distribution justice (export tables)

```{r}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study_t6_indep_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study_long_t6_comunas %>%
  select(idencuesta,ola,comuna,just_educ, merit_effort, merit_talent, ahead_family:educ,quintil1:sexo, ginilag22_17, gini_ypch_2022, gini_ypch, prop_univ, gini_gc, prop_pagado, pagadlag22_16=pagadolag22_16, total_mat_pagado, var_simce_comuna_rescaled, prom_simce_comuna_rescaled, univlag22_17, loginc_mean, logincomelag22_17) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
# Hipotesis
h1 <- "ola"
h2 <- "ola+merit_effort+merit_talent"
h3 <- "ola+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family"
h4 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family"
h5 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo"

h6 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17"
h7 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_univ+univlag22_17"
h8 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17"
h9 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_pagado+pagadlag22_16"
h10 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prom_simce_comuna_rescaled+var_simce_comuna_rescaled"
h11 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled"
h12 <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+loginc_mean+logincomelag22_17"

hfull <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+loginc_mean+logincomelag22_17"



# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1)
educ1 <- lmer(formula(paste0("just_educ~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ2 <- lmer(formula(paste0("just_educ~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ3 <- lmer(formula(paste0("just_educ~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ4 <- lmer(formula(paste0("just_educ~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ5 <- lmer(formula(paste0("just_educ~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ6 <- lmer(formula(paste0("just_educ~",h6,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ7 <- lmer(formula(paste0("just_educ~",h7,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ8 <- lmer(formula(paste0("just_educ~",h8,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ9 <- lmer(formula(paste0("just_educ~",h9,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ10 <- lmer(formula(paste0("just_educ~",h10,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ11 <- lmer(formula(paste0("just_educ~",h11,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ12 <- lmer(formula(paste0("just_educ~",h12,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ13 <- lmer(formula(paste0("just_educ~",hfull,"+(1|idencuesta)+(1|comuna)")),data = df_study1)

# Table 1: individual

#omit <- "(pos_id)|(edad)|(cuestion_mig)|(nation_t1)|(quintil1QNA)|(Intercept)"
texreg::htmlreg(list(educ1, educ2, educ3, educ4, educ5),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
                custom.coef.names = c("Intercepto",
                                      "ola 2017 <br> <i>(Ref. ola 2016)</i>",
                                      "ola 2018",
                                      "ola 2019",
                                      "ola 2022",
                                      "Merito: esfuerzo",
                                      "Merito: Inteligencia",
                                      "Goahead: trabajo duro",
                                      "Goahead: educacion",
                                      "Goahead: ambicion",
                                      "Goahead: Familia",
                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
                                      "Ed. técnica",
                                      "Ed. universitaria",
                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
                                      "Quintil 3",
                                      "Quintil 4",
                                      "Quintil 5",
                                      "Quintil NA",
                                      "Estatus social subjetivo",
                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
                                      "Pos. política: Derecha",
                                      "Pos. política: No se identifica",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Mujer <br> <i>(Ref. Hombre)</i>"),
                file = "output/tables/table1-individuales.html")
          #omit.coef = omit


webshot2::webshot(url ="output/tables/table1-individuales.html" ,file ="output/tables/table1-individuales.png")

```

```{r}
# table 2: contextuales
omit <- "(ola)|(merit_effort)|(merit_talent)|(ahead_hardwork)|(ahead_educ)|(ahead_ambition)|(ahead_family)|(educ)|(quintil1)|(ess)|(pos_id)|(edad)|(sexo)|(Intercept)"
texreg::htmlreg(list(educ6, educ7,educ8,educ9,educ10,educ11,educ12,educ13),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05", 
                omit.coef = omit,
                custom.coef.names = c(
                                      "Gini comunal",
                                      "Cambio gini 2022-2017",
                                      "Proporción educ universitaria",
                                      "Cambio prop. universitaria 2022-2017",
                                      "Proporción matrícula privada",
                                      "Cambio matrícula privada 2022-2016",
                                      "Promedio Simce comuna",
                                      "Varianza Simce comuna",
                                      "Ingreso comunal",
                                      "Cambio ingreso comunal 2022-2017"),
                file = "output/tables/table2-contextual.html")
          #omit.coef = omit

webshot2::webshot(url ="output/tables/table2-contextual.html" ,file ="output/tables/table2-contextual.png")

```


## Interacciones

```{r distribution-educ-context}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg,
               ggplot2
               )
load(file = here::here("input/data-proc/df_study_t6_ind_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study_long_t6_comunas %>%
  select(idencuesta,ola,comuna,just_educ, merit_effort, merit_talent, ahead_family:educ,quintil1:sexo, ginilag22_17, gini_ypch_2022, gini_ypch, prop_univ, gini_gc, prop_pagado, pagadlag22_16=pagadolag22_16, total_mat_pagado, var_simce_comuna_rescaled, prom_simce_comuna_rescaled, univlag22_17, loginc_mean, logincomelag22_17) %>% 
  na.omit() %>% 
  mutate(ola=as.factor(ola),
         sexo=as.factor(sexo)
         )
# Hipotesis
h1b <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled"
h2b <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+ola*merit_effort"
h3b <- "merit_effort+merit_talent+ola+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+merit_talent*ola"
h4b <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+ola*ahead_hardwork"
h5b <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+ola*ahead_educ"
h6b <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+ola*ahead_ambition"
h7b <- "ola+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+educ+quintil1+ess+pos_id+edad+sexo+gini_ypch+ginilag22_17+prop_univ+univlag22_17+prop_pagado+pagadlag22_16+prom_simce_comuna_rescaled+var_simce_comuna_rescaled+ola*ahead_family"

# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1)
educ1 <- lmer(formula(paste0("just_educ~",h1b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ2 <- lmer(formula(paste0("just_educ~",h2b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ3 <- lmer(formula(paste0("just_educ~",h3b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ4 <- lmer(formula(paste0("just_educ~",h4b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ5 <- lmer(formula(paste0("just_educ~",h5b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ6 <- lmer(formula(paste0("just_educ~",h6b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)
educ7 <- lmer(formula(paste0("just_educ~",h7b,"+(1|idencuesta)+(1|comuna)")),data = df_study1)

# table 3: interacciones
omit <- "(educ)|(quintil1)|(ess)|(pos_id)|(edad)|(sexo)|(Intercept)|(gini_ypch)|(ginilag22_17)|(prop_univ)|(univlag22_17)|(prop_pagado)|(pagadlag22_16)|(prom_simce_comuna_rescaled)|(var_simce_comuna_rescaled)"
texreg::htmlreg(list(educ1, educ2,educ3,educ4,educ5,educ6,educ7),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05",
                custom.coef.names = c("Intercepto",
                                      "2017",
                                      "2018",
                                      "2019",
                                      "2022",
                                      "Merito: esfuerzo",
                                      "Merito: Inteligencia",
                                      "Goahead: trabajo duro",
                                      "Goahead: educacion",
                                      "Goahead: ambicion",
                                      "Goahead: Familia",
                                      "Ed. media <br> <i>(Ref. Ed. básica)</i>",
                                      "Ed. técnica",
                                      "Ed. universitaria",
                                      "Quintil 2 <br> <i>(Ref. Quintil 1)</i>",
                                      "Quintil 3",
                                      "Quintil 4",
                                      "Quintil 5",
                                      "Quintil NA",
                                      "Estatus social subjetivo",
                                      "Pos. política: Centro <br> <i>(Ref. izquierda)</i>",
                                      "Pos. política: Derecha",
                                      "Pos. política: No se identifica",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Mujer <br> <i>(Ref. Hombre)</i>",
                                      "Gini comunal",
                                      "Cambio gini 2022-2017",
                                      "Proporción educ universitaria",
                                      "Cambio prop. universitaria 2022-2017",
                                      "Proporción matrícula privada",
                                      "Cambio matrícula privada 2022-2016",
                                      "Promedio Simce comuna",
                                      "Varianza Simce comuna",
                                      "2017*merit:esfuerzo",
                                      "2018*merit:esfuerzo",
                                      "2019*merit:esfuerzo",
                                      "2022*merit:esfuerzo",
                                      "2017*merit:talento",
                                      "2018*merit:talento",
                                      "2019*merit:talento",
                                      "2022*merit:talento",
                                      "2017*goahead:hardwork",
                                      "2018*goahead:hardwork",
                                      "2019*goahead:hardwork",
                                      "2022*goahead:hardwork",
                                      "2017*goahead:educ",
                                      "2018*goahead:educ",
                                      "2019*goahead:educ",
                                      "2022*goahead:educ",
                                      "2017*goahead:ambition",
                                      "2018*goahead:ambition",
                                      "2019*goahead:ambition",
                                      "2022*goahead:ambition",
                                      "2017*goahead:family",
                                      "2018*goahead:family",
                                      "2019*goahead:family",
                                      "2022*goahead:family"),
                file = "output/tables/table3-interac.html")
          #omit.coef = omit


webshot2::webshot(url ="output/tables/table3-interac.html" ,file ="output/tables/table3-interac.png")



## graph interact
#sjPlot::plot_model(educ2, type = "int", mdrt.values = "meansd")
predict<-interplot::interplot(m = educ2,var1 = "merit_effort",var2 = "ola",point = T)
predict_data <- predict$data[c(1, 2, 4, 6, 8), ]
predict_data <- predict_data %>% as.data.frame()

predict_data$value <- c("ola1", 
                             "ola2",
                             "ola3", 
                             "ola4",
                             "ola6")
  
predict_data$value <- factor(predict_data$value,
                   levels = c("ola1", 
                             "ola2",
                             "ola3", 
                             "ola4",
                             "ola6"),
                   labels = c("wave 1", 
                              "wave 2",
                              "wave 3",
                              "wave 4",
                              "wave 6"))

interact_effect <- predict_data %>% ggplot(aes(value, coef1)) +
  theme_bw(base_size = 14) +
  geom_point(size = 4)+
  geom_errorbar(aes(ymin=lb, ymax=ub),
                  width=0.2) +
  ylab("Coef") +
  xlab("")
interact_effect

ggsave(interact_effect, file="output/graphs/interact_effect.png", width = 7, height = 7)
```

## Ponderadores

```{r}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg
               )
load(file = here::here("input/data-proc/df_study_t6_ind_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study_long_t6_comunas %>%
  select(idencuesta,ola,comuna, ponderador_long_total,just_educ, des_perc, merit_effort, merit_talent, ahead_family:ahead_hardwork,education=educ,quintil1:sexo) %>% 
  na.omit() %>% 
  mutate(ola = as.factor(ola),
         ola_num = as.numeric(ola),
         ola_2=as.numeric(ola)^2,
         sexo=as.factor(sexo)
         )
# Hipotesis
h0 <- "des_perc"
h1 <- "des_perc+merit_effort+merit_talent"
h2 <- "des_perc+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family"
h3 <- "des_perc+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo"
h4 <- "des_perc+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola"
h5 <- "des_perc+merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola_num+ola_2"


# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ0 <- lmer(formula(paste0("just_educ~",h0,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ1 <- lmer(formula(paste0("just_educ~",h1,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ2 <- lmer(formula(paste0("just_educ~",h2,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ3 <- lmer(formula(paste0("just_educ~",h3,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ4 <- lmer(formula(paste0("just_educ~",h4,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ5 <- lmer(formula(paste0("just_educ~",h5,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)

# Table 1: individual

omit <- "(education)|(sexo)|(ess)"
texreg::htmlreg(list(educ0, educ1, educ2, educ3, educ4, educ5),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05. Models 4, 5, and 6 are controlled by educational level, gender and subjective social status with no significant effects.", 
                omit.coef = omit,
                custom.coef.names = c("Intercept",
                                      "Inequality perception",
                                      "Merit: effort",
                                      "Merit: Talent",
                                      "Getahead: Hardwork",
                                      "Getahead: Education",
                                      "Getahead: Ambition",
                                      "Getahead: Family",
                                      "Quintile 2 <br> <i>(Ref. Quintile 1)</i>",
                                      "Quintile 3",
                                      "Quintile 4",
                                      "Quintile 5",
                                      "Quintile NA",
                                      "Pol. pos: Center <br> <i>(Ref. Left)</i>",
                                      "Pol. pos: Right",
                                      "Pol. pos: Does not identify",
                                      "Edad 30-49 <br> <i>(Ref. 18-29)</i>",
                                      "Edad 50-64",
                                      "Edad 65 o más",
                                      "Wave 2017 <br> <i>(Ref. Wave 2016)</i>",
                                      "Wave 2018",
                                      "Wave 2019",
                                      "Wave 2022",
                                      "Wave",
                                      "Wave^2"),
                file = "output/tables/table1-individuales-pond-v2.html")
          #omit.coef = omit


webshot2::webshot(url ="output/tables/table1-individuales-pond-v2.html" ,file ="output/tables/table1-individuales-pond-v2.png")

```

## Interacciones

```{r distribution-educ-context}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg,
               ggplot2
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study_long_t6_comunas %>%
  select(idencuesta,ola,comuna, ponderador_long_total,just_educ, merit_effort, merit_talent, ahead_family:ahead_hardwork,education=educ,quintil1:sexo) %>% 
  na.omit() %>% 
  mutate(ola = as.factor(ola),
         ola_2=as.numeric(ola)^2,
         sexo=as.factor(sexo)
         )
# Hipotesis
h1b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola"
h2b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola*merit_effort"
h3b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola*merit_talent"
h4b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola*ahead_hardwork"
h5b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola*ahead_educ"
h6b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola*ahead_ambition"
h7b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola*ahead_family"

# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ1 <- lmer(formula(paste0("just_educ~",h1b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ2 <- lmer(formula(paste0("just_educ~",h2b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ3 <- lmer(formula(paste0("just_educ~",h3b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ4 <- lmer(formula(paste0("just_educ~",h4b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ5 <- lmer(formula(paste0("just_educ~",h5b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ6 <- lmer(formula(paste0("just_educ~",h6b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ7 <- lmer(formula(paste0("just_educ~",h7b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)

# table 3: interacciones
omit <- "(edad)|(education)|(sexo)|(ess)|(quintil1)|(pos_id)"
texreg::htmlreg(list(educ2,educ3,educ4,educ5,educ6,educ7),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05. All the models are controlled by educational level, age, gender, subjective social status, political position, and income quintile",
                omit.coef = omit,
                custom.coef.names = c("Intercept",
                                      "Merit: effort",
                                      "Merit: Talent",
                                      "Getahead: Hardwork",
                                      "Getahead: Education",
                                      "Getahead: Ambition",
                                      "Getahead: Family",
                                      "Wave 2017 <br> <i>(Ref. Wave 2016)</i>",
                                      "Wave 2018",
                                      "Wave 2019",
                                      "Wave 2022",
                                      "2017*merit:effort",
                                      "2018*merit:effort",
                                      "2019*merit:effort",
                                      "2022*merit:effort",
                                      "2017*merit:talent",
                                      "2018*merit:talent",
                                      "2019*merit:talent",
                                      "2022*merit:talent",
                                      "2017*getahead:hardwork",
                                      "2018*getahead:hardwork",
                                      "2019*getahead:hardwork",
                                      "2022*getahead:hardwork",
                                      "2017*getahead:education",
                                      "2018*getahead:education",
                                      "2019*getahead:education",
                                      "2022*getahead:education",
                                      "2017*getahead:ambition",
                                      "2018*getahead:ambition",
                                      "2019*getahead:ambition",
                                      "2022*getahead:ambition",
                                      "2017*getahead:family",
                                      "2018*getahead:family",
                                      "2019*getahead:family",
                                      "2022*getahead:family"),
                file = "output/tables/table3-interac_pond.html")
          #omit.coef = omit


webshot2::webshot(url ="output/tables/table3-interac_pond.html" ,file ="output/tables/table3-interac-pond.png")



## graph interact
#sjPlot::plot_model(educ2, type = "int", mdrt.values = "meansd")
predict<-interplot::interplot(m = educ2,var1 = "merit_effort",var2 = "ola",point = T)
predict_data <- predict$data[c(1, 2, 4, 6, 8), ]
predict_data <- predict_data %>% as.data.frame()

predict_data$value <- c("ola1", 
                             "ola2",
                             "ola3", 
                             "ola4",
                             "ola6")
  
predict_data$value <- factor(predict_data$value,
                   levels = c("ola1", 
                             "ola2",
                             "ola3", 
                             "ola4",
                             "ola6"),
                   labels = c("wave 1", 
                              "wave 2",
                              "wave 3",
                              "wave 4",
                              "wave 6"))

interact_effect <- predict_data %>% ggplot(aes(value, coef1)) +
  theme_bw(base_size = 14) +
  geom_point(size = 4)+
  geom_errorbar(aes(ymin=lb, ymax=ub),
                  width=0.2) +
  ylab("Coef") +
  xlab("")
interact_effect

ggsave(interact_effect, file="output/graphs/interact_effect-pond.png", width = 7, height = 7)
```

```{r distribution-educ-context}
#rm(list=ls())
#if (!require("pacman")) install.packages("pacman") # instalar pacman
                            # cargar librerias
pacman::p_load(dplyr,       # Manipulacion de datos
               knitr,
               kableExtra,
               summarytools,
               lme4,
               texreg,
               ggplot2
               )
load(file = here::here("input/data-proc/df_study1_long_comunas.RData"))

# generate analytical sample
df_study1 <- 
  df_study_long_t6_comunas %>%
  select(idencuesta,ola,comuna, ponderador_long_total,just_educ, merit_effort, merit_talent, ahead_family:ahead_hardwork,education=educ,quintil1:sexo) %>% 
  na.omit() %>% 
  mutate(ola = as.numeric(ola),
         ola_2=as.numeric(ola)^2,
         sexo=as.factor(sexo)
         )
# Hipotesis
h1b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2"
h2b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2+ola*merit_effort"
h3b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2+ola*merit_talent"
h4b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2+ola*ahead_hardwork"
h5b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2+ola*ahead_educ"
h6b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2+ola*ahead_ambition"
h7b <- "merit_effort+merit_talent+ahead_hardwork+ahead_educ+ahead_ambition+ahead_family+education+quintil1+ess+pos_id+edad+sexo+ola+ola_2+ola*ahead_family"

# A. Education distributive justice
educ.null <- lmer(formula(paste0("just_educ~","1 + (1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ1 <- lmer(formula(paste0("just_educ~",h1b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ2 <- lmer(formula(paste0("just_educ~",h2b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ3 <- lmer(formula(paste0("just_educ~",h3b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ4 <- lmer(formula(paste0("just_educ~",h4b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ5 <- lmer(formula(paste0("just_educ~",h5b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ6 <- lmer(formula(paste0("just_educ~",h6b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)
educ7 <- lmer(formula(paste0("just_educ~",h7b,"+(1|idencuesta)+(1|comuna)")),data = df_study1, weights = ponderador_long_total)

# table 3: interacciones
omit <- "(edad)|(education)|(sexo)|(ess)|(quintil1)|(pos_id)"
texreg::htmlreg(list(educ2,educ3,educ4,educ5,educ6,educ7),
                custom.note = "*** p < 0.001; ** p < 0.01; * p < 0.05. All the models are controlled by educational level, age, gender, subjective social status, political position, and income quintile",
                omit.coef = omit,
                custom.coef.names = c("Intercept",
                                      "Merit: effort",
                                      "Merit: Talent",
                                      "Getahead: Hardwork",
                                      "Getahead: Education",
                                      "Getahead: Ambition",
                                      "Getahead: Family",
                                      "Wave",
                                      "Wave^2",
                                      "wave*merit:effort",
                                      "wave*merit:talent",
                                      "Wave*getahead:hardwork",
                                      "Wave*getahead:education",
                                      "Wave*getahead:ambition",
                                      "Wave*getahead:family"),
                file = "output/tables/table3-interac_pond-cuadratic.html")
          #omit.coef = omit


webshot2::webshot(url ="output/tables/table3-interac_pond-cuadratic.html" ,file ="output/tables/table3-interac-pond-cuadratic.png")



## graph interact
#sjPlot::plot_model(educ2, type = "int", mdrt.values = "meansd")
predict<-interplot::interplot(m = educ2,var1 = "merit_effort",var2 = "ola",point = T)
predict_data <- predict$data[c(1, 2, 4, 6, 8), ]
predict_data <- predict_data %>% as.data.frame()

predict_data$value <- c("ola1", 
                             "ola2",
                             "ola3", 
                             "ola4",
                             "ola6")
  
predict_data$value <- factor(predict_data$value,
                   levels = c("ola1", 
                             "ola2",
                             "ola3", 
                             "ola4",
                             "ola6"),
                   labels = c("wave 1", 
                              "wave 2",
                              "wave 3",
                              "wave 4",
                              "wave 6"))

interact_effect <- predict_data %>% ggplot(aes(value, coef1)) +
  theme_bw(base_size = 14) +
  geom_point(size = 4)+
  geom_errorbar(aes(ymin=lb, ymax=ub),
                  width=0.2) +
  ylab("Coef") +
  xlab("")
interact_effect

ggsave(interact_effect, file="output/graphs/interact_effect-pond.png", width = 7, height = 7)
```
